classes: introduce BASEMENT_LIBS switch
The BASEMENT_LIBS switch can be set to control the build type and
installation of libraries. If unset, the default is dependent on the
overall built type as before: build shared libs on cross-compilation
and only static libs for host builds.

The switch might be set to one of the following values to override this
default:

 * shared - build and install shared libraries. Static libraries will
            still be installed if present, though.
 * static - build and install static libraries only. Shared libraries
            will never be installed.
 * both - Build and install both shared and static libraries.

diff --git a/classes/autotools.yaml b/classes/autotools.yaml
--- a/classes/autotools.yaml
+++ b/classes/autotools.yaml
@@ -1,6 +1,6 @@
 inherit: [cpackage, libtool, make, install]
 
-buildVars: [AUTOTOOLS_AUTO_STATIC]
+buildVars: [AUTOTOOLS_AUTO_STATIC, BASEMENT_LIBS]
 buildScript: |
     # $1 : source path
     autotoolsBuild()
@@ -16,6 +16,22 @@ buildScript: |
         # script will choke on these options.
         if [[ "${AUTOTOOLS_AUTO_STATIC:-yes}" == no ]] ; then
             : # do nothing
+        elif [[ -n "${BASEMENT_LIBS:-}" ]] ; then
+            case "$BASEMENT_LIBS" in
+                static)
+                    SHARED_STATIC=( "--disable-shared" "--enable-static" )
+                    ;;
+                shared)
+                    SHARED_STATIC=( "--enable-shared" "--disable-static" )
+                    ;;
+                both)
+                    SHARED_STATIC=( "--enable-shared" "--enable-static" )
+                    ;;
+                *)
+                    echo "Invalid BASEMENT_LIBS value: $BASEMENT_LIBS" >&2
+                    exit 1
+                    ;;
+            esac
         elif [[ "${AUTOCONF_BUILD:-unknown}" == "${AUTOCONF_HOST:-${AUTOCONF_BUILD:-unknown}}" ]]; then
             SHARED_STATIC=( "--disable-shared" "--enable-static" )
         else
diff --git a/classes/cmake.yaml b/classes/cmake.yaml
--- a/classes/cmake.yaml
+++ b/classes/cmake.yaml
@@ -1,7 +1,7 @@
 inherit: [cpackage, make, install]
 
 buildTools: [cmake]
-buildVars: [CC, CXX]
+buildVars: [CC, CXX, BASEMENT_LIBS]
 buildScript: |
     # Make sure CMake finds other stuff by its own logic too
     CMAKE_FIND_ROOT_PATH=
@@ -43,6 +43,24 @@ buildScript: |
     else
         BUILD_SHARED_LIBS=OFF
     fi
+
+    # The build of shared libraries can be overridden via BASEMENT_LIBS.
+    # Unfortunately there is no standard switch to control static libraries in
+    # CMake.
+    case "${BASEMENT_LIBS:-__unset__}" in
+        shared|both)
+            BUILD_SHARED_LIBS=ON
+            ;;
+        static)
+            BUILD_SHARED_LIBS=OFF
+            ;;
+        __unset__)
+            ;;
+        *)
+            echo "Invalid BASEMENT_LIBS value: $BASEMENT_LIBS" >&2
+            exit 1
+            ;;
+    esac
 
     # usage: cmakeBuild [-i <install_target>] [-m <make_target>] [-o <options>] [-O <options>] <source-path> [-DCMAKE_...]
     # $1 : source path
diff --git a/classes/install.yaml b/classes/install.yaml
--- a/classes/install.yaml
+++ b/classes/install.yaml
@@ -10,12 +10,29 @@ inherit: [strip]
 # be adapted to promote *.private dependencies to regular dependencies (We do
 # not pass --static to pkg-config.  Executables are still linked dynamically
 # because glibc cannot be linked statically).
+packageVars: [BASEMENT_LIBS]
 packageScript: |
     # Install shared libraries only when cross compiling. On host builds only
     # static libraries are installed.
     if [[ "${AUTOCONF_BUILD:-unknown}" != "${AUTOCONF_HOST:-${AUTOCONF_BUILD:-unknown}}" ]]; then
         INSTALL_SHARED=yes
     fi
+
+    # The user can override the defaults above
+    case "${BASEMENT_LIBS:-__unset__}" in
+        shared|both)
+            INSTALL_SHARED=yes
+            ;;
+        static)
+            INSTALL_SHARED=
+            ;;
+        __unset__)
+            ;;
+        *)
+            echo "Invalid BASEMENT_LIBS value: $BASEMENT_LIBS" >&2
+            exit 1
+            ;;
+    esac
 
     function _installJoinSpace { local IFS=" "; echo "$*"; }
     function _installJoinComma { echo -n "$1" ; shift ; printf "%s" "${@/#/, }"; }
