autoconf: add option to run aclocal
Apparently, autoreconf does not update any aclocal macros even if they
are available (devel::autoconf-archive). If a recipe needs updates of
these macros, it has to pass the -a option to autoconfReconfigure()
which runs "aclocal -I m4 --install" before autoreconf. Usually this is
not needed so it has to be a selective opt-in.

Optionally, the arguments to aclocal can be overridden by "-A".

diff --git a/classes/autoconf.yaml b/classes/autoconf.yaml
--- a/classes/autoconf.yaml
+++ b/classes/autoconf.yaml
@@ -21,8 +21,34 @@ checkoutSetup: |
         fi
     done
 
+    # Call autoreconf in current directory.
+    #
+    # Options: -a     Run "aclocal -I m4 --install" before autoreconf
+    #          -A     Add argument to aclocal, replacing the default ones
     autoconfReconfigure()
     {
+        local CALL_ACLOCAL=
+        local ACLOCAL_ARGS=()
+
+        # parse arguments
+        OPTIND=1
+        local opt
+        while getopts "aA:" opt ; do
+            case "$opt" in
+                a)
+                    CALL_ACLOCAL=y
+                    ;;
+                A)
+                    ACLOCAL_ARGS+=( "$OPTARG" )
+                    ;;
+                \?)
+                  echo "Invalid option: -$OPTARG" >&2
+                  exit 1
+                  ;;
+            esac
+        done
+        shift $(( OPTIND -1 ))
+
         if [[ ( ! -e configure ) || ( ! -e .autoreconf.stamp ) ||
               ( configure.ac -nt .autoreconf.stamp ) ]] ; then
             (
@@ -37,6 +63,16 @@ checkoutSetup: |
                 # suffix so that they can be garbage collected.
                 export SIMPLE_BACKUP_SUFFIX=.bob-backup
 
+                # Autoreconf will not replace existing autoconf-archive macros
+                # in the m4 directory. If that is needed, the recipe must
+                # force the update.
+                if [[ $CALL_ACLOCAL ]] ; then
+                    if [[ -n "${ACLOCAL_ARGS[@]:+set}" ]] ; then
+                        aclocal "${ACLOCAL_ARGS[@]}"
+                    else
+                        aclocal -I m4 --install
+                    fi
+                fi
                 autoreconf -vfi ${AUTOCONF_EXTRA_PKGS[@]+"${AUTOCONF_EXTRA_PKGS[@]/#/-I}"}
             )
             rm -rf autom4te.cache
